# Venture Funding with Deep Learning

You work as a risk management associate at Alphabet Soup, a venture capital firm. Alphabet Soup’s business team receives many funding applications from startups every day. This team has asked you to help them create a model that predicts whether applicants will be successful if funded by Alphabet Soup.

The business team has given you a CSV containing more than 34,000 organizations that have received funding from Alphabet Soup over the years. With your knowledge of machine learning and neural networks, you decide to use the features in the provided dataset to create a binary classifier model that will predict whether an applicant will become a successful business. The CSV file contains a variety of information about these businesses, including whether or not they ultimately became successful.

## Instructions:

The steps for this challenge are broken out into the following sections:

* Prepare the data for use on a neural network model.

* Compile and evaluate a binary classification model using a neural network.

* Optimize the neural network model.

### Prepare the Data for Use on a Neural Network Model 

Using your knowledge of Pandas and scikit-learn’s `StandardScaler()`, preprocess the dataset so that you can use it to compile and evaluate the neural network model later.

Open the starter code file, and complete the following data preparation steps:

1. Read the `applicants_data.csv` file into a Pandas DataFrame. Review the DataFrame, looking for categorical variables that will need to be encoded, as well as columns that could eventually define your features and target variables.   

2. Drop the “EIN” (Employer Identification Number) and “NAME” columns from the DataFrame, because they are not relevant to the binary classification model.
 
3. Encode the dataset’s categorical variables using `OneHotEncoder`, and then place the encoded variables into a new DataFrame.

4. Add the original DataFrame’s numerical variables to the DataFrame containing the encoded variables.

> **Note** To complete this step, you will employ the Pandas `concat()` function that was introduced earlier in this course. 

5. Using the preprocessed data, create the features (`X`) and target (`y`) datasets. The target dataset should be defined by the preprocessed DataFrame column “IS_SUCCESSFUL”. The remaining columns should define the features dataset. 

6. Split the features and target sets into training and testing datasets.

7. Use scikit-learn's `StandardScaler` to scale the features data.

### Compile and Evaluate a Binary Classification Model Using a Neural Network

Use your knowledge of TensorFlow to design a binary classification deep neural network model. This model should use the dataset’s features to predict whether an Alphabet Soup&ndash;funded startup will be successful based on the features in the dataset. Consider the number of inputs before determining the number of layers that your model will contain or the number of neurons on each layer. Then, compile and fit your model. Finally, evaluate your binary classification model to calculate the model’s loss and accuracy. 
 
To do so, complete the following steps:

1. Create a deep neural network by assigning the number of input features, the number of layers, and the number of neurons on each layer using Tensorflow’s Keras.

> **Hint** You can start with a two-layer deep neural network model that uses the `relu` activation function for both layers.

2. Compile and fit the model using the `binary_crossentropy` loss function, the `adam` optimizer, and the `accuracy` evaluation metric.

> **Hint** When fitting the model, start with a small number of epochs, such as 20, 50, or 100.

3. Evaluate the model using the test data to determine the model’s loss and accuracy.

4. Save and export your model to an HDF5 file, and name the file `AlphabetSoup.h5`. 

### Optimize the Neural Network Model

Using your knowledge of TensorFlow and Keras, optimize your model to improve the model's accuracy. Even if you do not successfully achieve a better accuracy, you'll need to demonstrate at least two attempts to optimize the model. You can include these attempts in your existing notebook. Or, you can make copies of the starter notebook in the same folder, rename them, and code each model optimization in a new notebook. 

> **Note** You will not lose points if your model does not achieve a high accuracy, as long as you make at least two attempts to optimize the model.

To do so, complete the following steps:

1. Define at least three new deep neural network models (the original plus 2 optimization attempts). With each, try to improve on your first model’s predictive accuracy.

> **Rewind** Recall that perfect accuracy has a value of 1, so accuracy improves as its value moves closer to 1. To optimize your model for a predictive accuracy as close to 1 as possible, you can use any or all of the following techniques:
>
> * Adjust the input data by dropping different features columns to ensure that no variables or outliers confuse the model.
>
> * Add more neurons (nodes) to a hidden layer.
>
> * Add more hidden layers.
>
> * Use different activation functions for the hidden layers.
>
> * Add to or reduce the number of epochs in the training regimen.

2. After finishing your models, display the accuracy scores achieved by each model, and compare the results.

3. Save each of your models as an HDF5 file.

In [1]:
# Imports
import pandas as pd
from pathlib import Path
import tensorflow as tf
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,OneHotEncoder
import warnings
warnings.filterwarnings('ignore')

C:\Users\JBarr\anaconda3\envs\dev\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\JBarr\anaconda3\envs\dev\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\JBarr\anaconda3\envs\dev\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\JBarr\anaconda3\envs\dev\lib\site-packages\tensorflow\python\framework\dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
C:\Users\JBarr\anaconda3\envs\dev\lib\site-packages\tensorflow\python\framework\dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
C:\Users\JBarr\anaconda3\envs\dev\lib\site-packages\tensorflow\python\framework\dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
C:\Users\JBarr\anaconda3\envs\dev\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\JBarr\anaconda3\envs\dev\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\JBarr\anaconda3\envs\dev\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\JBarr\anaconda3\envs\dev\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
C:\Users\JBarr\anaconda3\envs\dev\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
C:\Users\JBarr\anaconda3\envs\dev\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])

---

## Prepare the data to be used on a neural network model

### Step 1: Read the `applicants_data.csv` file into a Pandas DataFrame. Review the DataFrame, looking for categorical variables that will need to be encoded, as well as columns that could eventually define your features and target variables.

In [2]:
# Read the applicants_data.csv file from the Resources folder into a Pandas DataFrame
applicant_data_df = pd.read_csv(
    Path('applicants_data.csv'))
# YOUR CODE HERE

# Review the DataFrame
# YOUR CODE HERE
applicant_data_df.head(5)

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [3]:
# Review the data types associated with the columns
# YOUR CODE HERE
applicant_data_df.dtypes

EIN                        int64
NAME                      object
APPLICATION_TYPE          object
AFFILIATION               object
CLASSIFICATION            object
USE_CASE                  object
ORGANIZATION              object
STATUS                     int64
INCOME_AMT                object
SPECIAL_CONSIDERATIONS    object
ASK_AMT                    int64
IS_SUCCESSFUL              int64
dtype: object

### Step 2: Drop the “EIN” (Employer Identification Number) and “NAME” columns from the DataFrame, because they are not relevant to the binary classification model.

In [4]:
# Drop the 'EIN' and 'NAME' columns from the DataFrame
applicant_data_df_droped = applicant_data_df.drop(columns=['EIN', 'NAME'])
# YOUR CODE HERE

In [5]:
# Review the DataFrame
# YOUR CODE HERE
applicant_data_df_droped.head()

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

t test, chi-sqd, corr

In [6]:
# Create a OneHotEncoder instance
enc = OneHotEncoder(sparse=False)

### Step 3: Encode the dataset’s categorical variables using `OneHotEncoder`, and then place the encoded variables into a new DataFrame.

In [7]:
# Create a list of categorical variables 
categorical = list(applicant_data_df_droped.dtypes[applicant_data_df_droped.dtypes=='object'].index)

In [8]:
#cats_vars = ['APPLICATION_TYPE', 'AFFILIATION', 'CLASSIFICATION', 'USE_CASE', 'ORGANIZATION', 'STATUS', 'INCOME_AMT', 'SPECIAL_CONSIDERATIONS', 'ASK_AMT', 'IS_SUCCESSFUL']

In [9]:
# Encode the categorcal variables using OneHotEncoder
cats_encoded = enc.fit_transform(applicant_data_df_droped[categorical])
# Display the categorical variables list
# YOUR CODE HERE
cats_encoded

array([[1., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       ...,
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 1., 0.]])

In [10]:
# Create a DataFrame with the encoded variables
encoded_df_new = pd.DataFrame(cats_encoded,
                         columns=enc.get_feature_names(categorical)
                                                                      )
                         
# YOUR CODE HERE

# Review the DataFrame
# YOUR CODE HERE
encoded_df_new

,APPLICATION_TYPE_T10,APPLICATION_TYPE_T12,APPLICATION_TYPE_T13,APPLICATION_TYPE_T14,APPLICATION_TYPE_T15,APPLICATION_TYPE_T17,APPLICATION_TYPE_T19,APPLICATION_TYPE_T2,APPLICATION_TYPE_T25,APPLICATION_TYPE_T29,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
34295,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
34296,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
34297,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
34298,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0

### Step 4: Add the original DataFrame’s numerical variables to the DataFrame containing the encoded variables.

> **Note** To complete this step, you will employ the Pandas `concat()` function that was introduced earlier in this course.

In [11]:
# Add the numerical variables from the original DataFrame to the one-hot encoding DataFrame
encoded_df =  pd.concat([applicant_data_df[['ASK_AMT', 'IS_SUCCESSFUL','STATUS']], encoded_df_new], axis=1)# YOUR CODE HERE

# Review the Dataframe
# YOUR CODE HERE
encoded_df

,ASK_AMT,IS_SUCCESSFUL,STATUS,APPLICATION_TYPE_T10,APPLICATION_TYPE_T12,APPLICATION_TYPE_T13,APPLICATION_TYPE_T14,APPLICATION_TYPE_T15,APPLICATION_TYPE_T17,APPLICATION_TYPE_T19,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,5000,1,1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,108590,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,5000,0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,6692,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,142590,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,5000,0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
34295,5000,0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
34296,5000,0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
34297,5000,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
34298,36500179,0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0

### Step 5: Using the preprocessed data, create the features (`X`) and target (`y`) datasets. The target dataset should be defined by the preprocessed DataFrame column “IS_SUCCESSFUL”. The remaining columns should define the features dataset.

In [12]:
# Define the target set y using the IS_SUCCESSFUL column
y = encoded_df['IS_SUCCESSFUL']
# YOUR CODE HERE

# Display a sample of y
# YOUR CODE HERE
y

0        1
1        1
2        0
3        1
4        1
        ..
34294    0
34295    0
34296    0
34297    1
34298    0
Name: IS_SUCCESSFUL, Length: 34299, dtype: int64

In [13]:
# Define features set X by selecting all columns but IS_SUCCESSFUL
X = encoded_df.drop(columns=['IS_SUCCESSFUL'])
# YOUR CODE HERE

# Review the features DataFrame
# YOUR CODE HERE
X

,ASK_AMT,STATUS,APPLICATION_TYPE_T10,APPLICATION_TYPE_T12,APPLICATION_TYPE_T13,APPLICATION_TYPE_T14,APPLICATION_TYPE_T15,APPLICATION_TYPE_T17,APPLICATION_TYPE_T19,APPLICATION_TYPE_T2,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,5000,1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,108590,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,5000,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,6692,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,142590,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,5000,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
34295,5000,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
34296,5000,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
34297,5000,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
34298,36500179,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0

### Step 6: Split the features and target sets into training and testing datasets.

In [14]:
# Split the preprocessed data into a training and testing dataset
# Assign the function a random_state equal to 1
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state= 1)
# YOUR CODE HERE

### Step 7: Use scikit-learn's `StandardScaler` to scale the features data.

In [15]:
# Create a StandardScaler instance
scaler = StandardScaler()
# YOUR CODE HERE

In [16]:
# Fit the scaler to the features training dataset
X_scaler = scaler.fit(X_train)  
# YOUR CODE HERE

In [17]:
# Fit the scaler to the features training dataset
X_train_scaled = X_scaler.transform(X_train)
# YOUR CODE HERE
X_test_scaled = X_scaler.transform(X_test)
# YOUR CODE HERE

---

## Compile and Evaluate a Binary Classification Model Using a Neural Network

### Step 1: Create a deep neural network by assigning the number of input features, the number of layers, and the number of neurons on each layer using Tensorflow’s Keras.

> **Hint** You can start with a two-layer deep neural network model that uses the `relu` activation function for both layers.

In [18]:
# Define the the number of inputs (features) to the model
number_input_features = 116
# YOUR CODE HERE

# Review the number of features
number_input_features

116

In [19]:
# Define the number of neurons in the output layer
number_output_neurons = 58
# YOUR CODE HERE

In [20]:
# Define the number of hidden nodes for the first hidden layer
hidden_nodes_layer1 = 75
# YOUR CODE HERE

# Review the number hidden nodes in the first layer
hidden_nodes_layer1

75

In [21]:
# Define the number of hidden nodes for the second hidden layer
hidden_nodes_layer2 = 55
# YOUR CODE HERE

# Review the number hidden nodes in the second layer
hidden_nodes_layer2

55

In [22]:
# Create the Sequential model instance
nn = Sequential()
# YOUR CODE HERE

In [23]:
# Add the first hidden layer
# YOUR CODE HERE
nn.add(
    Dense(input_dim=number_input_features, units=hidden_nodes_layer1, activation="relu"))

WARNING:tensorflow:From C:\Users\JBarr\anaconda3\envs\dev\lib\site-packages\tensorflow\python\ops\init_ops.py:1251: calling VarianceScaling.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor

In [24]:
# Add the second hidden layer
# YOUR CODE HERE
nn.add(
    Dense(units=hidden_nodes_layer2, activation='relu'))

In [25]:
# Add the output layer to the model specifying the number of output neurons and activation function
# YOUR CODE HERE
nn.add(Dense(units=1, activation="sigmoid"))

In [26]:
# Display the Sequential model summary
# YOUR CODE HERE
nn.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense (Dense)                (None, 75)                8775
_________________________________________________________________
dense_1 (Dense)              (None, 55)                4180
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 56
=================================================================
Total params: 13,011
Trainable params: 13,011
Non-trainable params: 0
_________________________________________________________________

### Step 2: Compile and fit the model using the `binary_crossentropy` loss function, the `adam` optimizer, and the `accuracy` evaluation metric.

In [27]:
# Compile the Sequential model
# YOUR CODE HERE
# Compile the model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

# Train the model
# Fit the model using 50 epochs and the training data
# YOUR CODE HERE

model_1 = nn.fit(X_train_scaled, y_train, validation_split=0.3, epochs=50)

WARNING:tensorflow:From C:\Users\JBarr\anaconda3\envs\dev\lib\site-packages\tensorflow\python\ops\nn_impl.py:180: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
Train on 18006 samples, validate on 7718 samples
Epoch 1/50
18006/18006 [==============================] - 1s 32us/sample - loss: 0.5804 - acc: 0.7193 - val_loss: 0.5563 - val_acc: 0.7331
Epoch 2/50
18006/18006 [==============================] - 0s 27us/sample - loss: 0.5573 - acc: 0.7249 - val_loss: 0.5512 - val_acc: 0.7361
Epoch 3/50
18006/18006 [==============================] - 0s 27us/sample - loss: 0.5536 - acc: 0.7276 - val_loss: 0.5572 - val_acc: 0.7330
Epoch 4/50
18006/18006 [==============================] - 0s 26us/sample - loss: 0.5520 - acc: 0.7276 - val_loss: 0.5546 - val_acc: 0.7331
Epoch 5/50
18006/18006 [==============================] - 0s 26us/sample - loss: 0.5494 - acc: 0.7290 - val_loss: 0.5484 - val_acc: 0.7389
Epoch 6/50
18006/18006 [==============================] - 0s 27us/sample - loss: 0.5483 - acc: 0.7290 - val_loss: 0.5532 - val_acc: 0.7354
Epoch 7/50
18006/18006 [==============================] - 0s 27us/sample - loss: 0.5466 - acc: 0.7304 - val_loss: 0.5556 - val_acc: 0.7357
Epoch 8/50
18006/18006 [==============================] - 0s 26us/sample - loss: 0.5464 - acc: 0.7293 - val_loss: 0.5508 - val_acc: 0.7381
Epoch 9/50
18006/18006 [==============================] - 0s 27us/sample - loss: 0.5450 - acc: 0.7312 - val_loss: 0.5579 - val_acc: 0.7340
Epoch 10/50
18006/18006 [==============================] - 0s 27us/sample - loss: 0.5445 - acc: 0.7323 - val_loss: 0.5526 - val_acc: 0.7379
Epoch 11/50
18006/18006 [==============================] - 0s 27us/sample - loss: 0.5438 - acc: 0.7308 - val_loss: 0.5533 - val_acc: 0.7359
Epoch 12/50
18006/18006 [==============================] - 0s 27us/sample - loss: 0.5435 - acc: 0.7326 - val_loss: 0.5540 - val_acc: 0.7376
Epoch 13/50
18006/18006 [==============================] - 0s 27us/sample - loss: 0.5426 - acc: 0.7329 - val_loss: 0.5584 - val_acc: 0.7362
Epoch 14/50
18006/18006 [==============================] - 0s 27us/sample - loss: 0.5427 - acc: 0.7313 - val_loss: 0.5558 - val_acc: 0.7358
Epoch 15/50
18006/18006 [==============================] - 0s 27us/sample - loss: 0.5414 - acc: 0.7325 - val_loss: 0.5621 - val_acc: 0.7315
Epoch 16/50
18006/18006 [==============================] - 0s 27us/sample - loss: 0.5412 - acc: 0.7337 - val_loss: 0.5590 - val_acc: 0.7330
Epoch 17/50
18006/18006 [==============================] - 0s 27us/sample - loss: 0.5407 - acc: 0.7356 - val_loss: 0.5590 - val_acc: 0.7341
Epoch 18/50
18006/18006 [==============================] - 0s 27us/sample - loss: 0.5400 - acc: 0.7341 - val_loss: 0.5544 - val_acc: 0.7375
Epoch 19/50
18006/18006 [==============================] - 0s 27us/sample - loss: 0.5396 - acc: 0.7359 - val_loss: 0.5593 - val_acc: 0.7366
Epoch 20/50
18006/18006 [==============================] - 0s 27us/sample - loss: 0.5396 - acc: 0.7356 - val_loss: 0.5625 - val_acc: 0.7322
Epoch 21/50
18006/18006 [==============================] - 0s 27us/sample - loss: 0.5390 - acc: 0.7341 - val_loss: 0.5559 - val_acc: 0.7334
Epoch 22/50
18006/18006 [==============================] - 0s 26us/sample - loss: 0.5385 - acc: 0.7354 - val_loss: 0.5599 - val_acc: 0.7352
Epoch 23/50
18006/18006 [==============================] - 0s 26us/sample - loss: 0.5382 - acc: 0.7373 - val_loss: 0.5596 - val_acc: 0.7348
Epoch 24/50
18006/18006 [==============================] - 0s 27us/sample - loss: 0.5378 - acc: 0.7371 - val_loss: 0.5570 - val_acc: 0.7340
Epoch 25/50
18006/18006 [==============================] - 0s 26us/sample - loss: 0.5377 - acc: 0.7355 - val_loss: 0.5567 - val_acc: 0.7363
Epoch 26/50
18006/18006 [==============================] - 0s 27us/sample - loss: 0.5375 - acc: 0.7376 - val_loss: 0.5570 - val_acc: 0.7343
Epoch 27/50
18006/18006 [==============================] - 0s 27us/sample - loss: 0.5373 - acc: 0.7370 - val_loss: 0.5590 - val_acc: 0.7368
Epoch 28/50
18006/18006 [==============================] - 0s 27us/sample - loss: 0.5366 - acc: 0.7357 - val_loss: 0.5572 - val_acc: 0.7346
Epoch 29/50
18006/18006 [==============================] - 0s 27us/sample - loss: 0.5369 - acc: 0.7366 - val_loss: 0.5574 - val_acc: 0.7380
Epoch 30/50
18006/18006 [==============================] - 0s 27us/sample - loss: 0.5362 - acc: 0.7370 - val_loss: 0.5634 - val_acc: 0.7363
Epoch 31/50
18006/18006 [==============================] - 0s 26us/sample - loss: 0.5365 - acc: 0.7380 - val_loss: 0.5597 - val_acc: 0.7334
Epoch 32/50
18006/18006 [==============================] - 1s 29us/sample - loss: 0.5354 - acc: 0.7363 - val_loss: 0.5626 - val_acc: 0.7361
Epoch 33/50
18006/18006 [==============================] - 0s 26us/sample - loss: 0.5355 - acc: 0.7376 - val_loss: 0.5616 - val_acc: 0.7346
Epoch 34/50
18006/18006 [==============================] - 0s 26us/sample - loss: 0.5357 - acc: 0.7369 - val_loss: 0.5605 - val_acc: 0.7381
Epoch 35/50
18006/18006 [==============================] - 0s 27us/sample - loss: 0.5351 - acc: 0.7370 - val_loss: 0.5631 - val_acc: 0.7383
Epoch 36/50
18006/18006 [==============================] - 0s 26us/sample - loss: 0.5349 - acc: 0.7384 - val_loss: 0.5612 - val_acc: 0.7350
Epoch 37/50
18006/18006 [==============================] - 0s 27us/sample - loss: 0.5344 - acc: 0.7383 - val_loss: 0.5633 - val_acc: 0.7344
Epoch 38/50
18006/18006 [==============================] - 0s 27us/sample - loss: 0.5341 - acc: 0.7375 - val_loss: 0.5642 - val_acc: 0.7343
Epoch 39/50
18006/18006 [==============================] - 0s 27us/sample - loss: 0.5345 - acc: 0.7370 - val_loss: 0.5659 - val_acc: 0.7339
Epoch 40/50
18006/18006 [==============================] - 0s 26us/sample - loss: 0.5343 - acc: 0.7391 - val_loss: 0.5638 - val_acc: 0.7375
Epoch 41/50
18006/18006 [==============================] - 0s 26us/sample - loss: 0.5334 - acc: 0.7396 - val_loss: 0.5655 - val_acc: 0.7345
Epoch 42/50
18006/18006 [==============================] - 0s 27us/sample - loss: 0.5336 - acc: 0.7391 - val_loss: 0.5633 - val_acc: 0.7394
Epoch 43/50
18006/18006 [==============================] - 0s 27us/sample - loss: 0.5332 - acc: 0.7387 - val_loss: 0.5631 - val_acc: 0.7353
Epoch 44/50
18006/18006 [==============================] - 0s 27us/sample - loss: 0.5330 - acc: 0.7390 - val_loss: 0.5630 - val_acc: 0.7368
Epoch 45/50
18006/18006 [==============================] - 0s 27us/sample - loss: 0.5333 - acc: 0.7384 - val_loss: 0.5687 - val_acc: 0.7349
Epoch 46/50
18006/18006 [==============================] - 0s 27us/sample - loss: 0.5322 - acc: 0.7390 - val_loss: 0.5699 - val_acc: 0.7343
Epoch 47/50
18006/18006 [==============================] - 0s 27us/sample - loss: 0.5326 - acc: 0.7385 - val_loss: 0.5710 - val_acc: 0.7353
Epoch 48/50
18006/18006 [==============================] - 0s 27us/sample - loss: 0.5326 - acc: 0.7384 - val_loss: 0.5697 - val_acc: 0.7348
Epoch 49/50
18006/18006 [==============================] - 0s 28us/sample - loss: 0.5322 - acc: 0.7404 - val_loss: 0.5734 - val_acc: 0.7337
Epoch 50/50
18006/18006 [==============================] - 0s 26us/sample - loss: 0.5322 - acc: 0.7396 - val_loss: 0.5686 - val_acc: 0.7353

### Step 3: Evaluate the model using the test data to determine the model’s loss and accuracy.

In [28]:
# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled, y_test, verbose=2)
# YOUR CODE HERE

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

8575/8575 - 0s - loss: 0.5576 - acc: 0.7279
Loss: 0.5576005564973237, Accuracy: 0.7279300093650818

### Step 4: Save and export your model to an HDF5 file, and name the file `AlphabetSoup.h5`.

In [29]:
# Set the model's file path
file_path = Path("venture_funding_with_deep_learning.ipynb")

# Export your model to a HDF5 file
AlphabetSoup = nn.save(file_path)

---

## Optimize the neural network model

### Step 1: Define at least three new deep neural network models (resulting in the original plus 3 optimization attempts). With each, try to improve on your first model’s predictive accuracy.

> **Rewind** Recall that perfect accuracy has a value of 1, so accuracy improves as its value moves closer to 1. To optimize your model for a predictive accuracy as close to 1 as possible, you can use any or all of the following techniques:
>
> * Adjust the input data by dropping different features columns to ensure that no variables or outliers confuse the model.
>
> * Add more neurons (nodes) to a hidden layer.
>
> * Add more hidden layers.
>
> * Use different activation functions for the hidden layers.
>
> * Add to or reduce the number of epochs in the training regimen.

### Alternative Model 1

In [30]:
# Define the the number of inputs (features) to the model
number_input_features_ = len(X_train.iloc[0])

# Review the number of features
number_input_features

116

In [31]:
# Define the number of neurons in the output layer
number_output_neurons_A1 = 47
# YOUR CODE HERE

In [32]:
# Define the number of hidden nodes for the first hidden layer
hidden_nodes_layer1_A1 = 70
# YOUR CODE HERE

# Review the number of hidden nodes in the first layer
hidden_nodes_layer1_A1

70

In [33]:
# Create the Sequential model instance
nn_A1 = Sequential()
# YOUR CODE HERE

In [34]:
# First hidden layer
# YOUR CODE HERE
nn_A1.add(
    Dense(input_dim = number_input_features_, units=number_output_neurons_A1, activation='relu'))

# Output layer
# YOUR CODE HERE
nn_A1.add(Dense(units=1, activation="linear"))

# Check the structure of the model
# YOUR CODE HERE
dir(nn_A1)

['_TF_MODULE_IGNORED_PROPERTIES',
 '__call__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_activity_regularizer',
 '_add_inbound_node',
 '_add_unique_metric_name',
 '_add_variable_with_custom_getter',
 '_all_metrics_tensors',
 '_assert_compile_was_called',
 '_assert_weights_created',
 '_base_init',
 '_build_input_shape',
 '_cache_output_metric_attributes',
 '_call_convention',
 '_call_fn_args',
 '_call_metric_fn',
 '_callable_losses',
 '_check_trainable_weights_consistency',
 '_checkpoint_dependencies',
 '_ckpt_saved_epoch',
 '_clear_losses',
 '_compile_distribution',
 '_compile_eagerly',
 '_compile_weights_loss_and_weighted_metrics',
 '_compute_output_and_mask_jointly',
 '_deferred_dependencies',
 '_determine_call_convention',
 '_distribution_standardize_user_data',
 '_distribution_strategy',
 '_dtype',
 '_dynamic',
 '_eager_add_metric',
 '_eager_losses',
 '_expects_training_arg',
 '_feed_input_names',
 '_feed_input_shapes',
 '_feed_inputs',
 '_feed_loss_fns',
 '_feed_output_names',
 '_feed_output_shapes',
 '_feed_sample_weights',
 '_feed_targets',
 '_flatten',
 '_gather_children_attribute',
 '_gather_saveables_for_checkpoint',
 '_get_callback_model',
 '_get_existing_metric',
 '_get_node_attribute_at_index',
 '_graph',
 '_handle_activity_regularization',
 '_handle_deferred_dependencies',
 '_handle_metrics',
 '_handle_per_output_metrics',
 '_handle_weight_regularization',
 '_inbound_nodes',
 '_init_graph_network',
 '_init_metric_attributes',
 '_init_set_name',
 '_init_subclassed_network',
 '_input_coordinates',
 '_input_layers',
 '_inputs_from_call_args',
 '_insert_layers',
 '_is_compiled',
 '_is_graph_network',
 '_is_layer',
 '_keras_api_names',
 '_keras_api_names_v1',
 '_layer_call_argspecs',
 '_layers',
 '_layers_by_depth',
 '_list_functions_for_serialization',
 '_lookup_dependency',
 '_loss_weights_list',
 '_losses',
 '_make_callback_model',
 '_make_execution_function',
 '_make_predict_function',
 '_make_test_function',
 '_make_train_function',
 '_maybe_build',
 '_maybe_create_attribute',
 '_maybe_initialize_trackable',
 '_maybe_load_initial_epoch_from_ckpt',
 '_metrics',
 '_metrics_tensors',
 '_mixed_precision_policy',
 '_name',
 '_name_based_attribute_restore',
 '_name_based_restores',
 '_name_scope',
 '_nested_inputs',
 '_nested_outputs',
 '_network_nodes',
 '_no_dependency',
 '_nodes_by_depth',
 '_non_trainable_weights',
 '_obj_reference_counts',
 '_outbound_nodes',
 '_output_coordinates',
 '_output_layers',
 '_output_loss_metrics',
 '_output_mask_cache',
 '_output_shape_cache',
 '_output_tensor_cache',
 '_preload_simple_restoration',
 '_prepare_output_masks',
 '_prepare_sample_weights',
 '_prepare_skip_target_masks',
 '_prepare_total_loss',
 '_process_target_tensor_for_compile',
 '_recompile_weights_loss_and_weighted_metrics',
 '_restore_from_checkpoint_position',
 '_reuse',
 '_run_eagerly',
 '_run_internal_graph',
 '_sample_weight_modes',
 '_scope',
 '_self_name_based_restores',
 '_self_setattr_tracking',
 '_self_unconditional_checkpoint_dependencies',
 '_self_unconditional_deferred_dependencies',
 '_self_unconditional_dependency_names',
 '_self_update_uid',
 '_set_connectivity_metadata_',
 '_set_dtype_and_policy',
 '_set_input_attrs',
 '_set_inputs',
 '_set_mask_metadata',
 '_set_metric_attributes',
 '_set_output_attrs',
 '_set_output_names',
 '_set_per_output_metric_attributes',
 '_setattr_tracking',
 '_should_compute_mask',
 '_single_restoration_from_checkpoint_position',
 '_standardize_user_data',
 '_symbolic_add_metric',
 '_symbolic_call',
 '_targets',
 '_tf_api_names',
 '_tf_api_names_v1',
 '_track_layers',
 '_track_trackable',
 '_trackable_saver',
 '_trainable',
 '_trainable_weights',
 '_unconditional_checkpoint_dependencies',
 '_unconditional_dependency_names',
 '_unpack_validation_data',
 '_update_sample_weight_modes',
 '_update_uid',
 '_updated_config',
 '_updates',
 '_validate_compile_param_for_distribution_strategy',
 '_validate_graph_inputs_and_outputs',
 '_validate_or_infer_batch_size',
 'activity_regularizer',
 'add',
 'add_loss',
 'add_metric',
 'add_update',
 'add_variable',
 'add_weight',
 'apply',
 'build',
 'built',
 'call',
 'compile',
 'compute_mask',
 'compute_output_shape',
 'count_params',
 'dtype',
 'dynamic',
 'evaluate',
 'evaluate_generator',
 'fit',
 'fit_generator',
 'from_config',
 'get_config',
 'get_input_at',
 'get_input_mask_at',
 'get_input_shape_at',
 'get_layer',
 'get_losses_for',
 'get_output_at',
 'get_output_mask_at',
 'get_output_shape_at',
 'get_updates_for',
 'get_weights',
 'inbound_nodes',
 'input',
 'input_mask',
 'input_names',
 'input_shape',
 'input_spec',
 'inputs',
 'layers',
 'load_weights',
 'losses',
 'metrics',
 'metrics_names',
 'name',
 'name_scope',
 'non_trainable_variables',
 'non_trainable_weights',
 'optimizer',
 'outbound_nodes',
 'output',
 'output_mask',
 'output_names',
 'output_shape',
 'outputs',
 'pop',
 'predict',
 'predict_classes',
 'predict_generator',
 'predict_on_batch',
 'predict_proba',
 'reset_metrics',
 'reset_states',
 'run_eagerly',
 'sample_weights',
 'save',
 'save_weights',
 'set_weights',
 'state_updates',
 'stateful',
 'submodules',
 'summary',
 'supports_masking',
 'test_on_batch',
 'to_json',
 'to_yaml',
 'train_on_batch',
 'trainable',
 'trainable_variables',
 'trainable_weights',
 'updates',
 'variables',
 'weights',
 'with_name_scope']

In [77]:
# Compile the Sequential model
nn_A1.compile(loss="mean_squared_error", optimizer="adam", metrics=["accuracy"])

In [78]:
# Fit the model using 50 epochs and the training data
fit_model_A1 = nn_A1.fit(X_train_scaled, y_train, epochs=50, verbose=2)
# YOUR CODE HERE

Epoch 1/50
25724/25724 - 1s - loss: 0.1807 - acc: 0.7406
Epoch 2/50
25724/25724 - 0s - loss: 0.1805 - acc: 0.7406
Epoch 3/50
25724/25724 - 0s - loss: 0.1806 - acc: 0.7407
Epoch 4/50
25724/25724 - 0s - loss: 0.1815 - acc: 0.7402
Epoch 5/50
25724/25724 - 0s - loss: 0.1814 - acc: 0.7392
Epoch 6/50
25724/25724 - 0s - loss: 0.1806 - acc: 0.7405
Epoch 7/50
25724/25724 - 0s - loss: 0.1809 - acc: 0.7402
Epoch 8/50
25724/25724 - 0s - loss: 0.1801 - acc: 0.7395
Epoch 9/50
25724/25724 - 0s - loss: 0.1807 - acc: 0.7388
Epoch 10/50
25724/25724 - 0s - loss: 0.1806 - acc: 0.7399
Epoch 11/50
25724/25724 - 1s - loss: 0.1804 - acc: 0.7407
Epoch 12/50
25724/25724 - 0s - loss: 0.1806 - acc: 0.7401
Epoch 13/50
25724/25724 - 1s - loss: 0.1801 - acc: 0.7403
Epoch 14/50
25724/25724 - 1s - loss: 0.1810 - acc: 0.7407
Epoch 15/50
25724/25724 - 0s - loss: 0.1800 - acc: 0.7406
Epoch 16/50
25724/25724 - 1s - loss: 0.1805 - acc: 0.7402
Epoch 17/50
25724/25724 - 1s - loss: 0.1806 - acc: 0.7400
Epoch 18/50
25724/25724 - 1s - loss: 0.1800 - acc: 0.7397
Epoch 19/50
25724/25724 - 1s - loss: 0.1802 - acc: 0.7408
Epoch 20/50
25724/25724 - 1s - loss: 0.1801 - acc: 0.7402
Epoch 21/50
25724/25724 - 1s - loss: 0.1798 - acc: 0.7394
Epoch 22/50
25724/25724 - 1s - loss: 0.1806 - acc: 0.7402
Epoch 23/50
25724/25724 - 1s - loss: 0.1804 - acc: 0.7402
Epoch 24/50
25724/25724 - 1s - loss: 0.1799 - acc: 0.7390
Epoch 25/50
25724/25724 - 1s - loss: 0.1799 - acc: 0.7404
Epoch 26/50
25724/25724 - 1s - loss: 0.1803 - acc: 0.7399
Epoch 27/50
25724/25724 - 1s - loss: 0.1806 - acc: 0.7404
Epoch 28/50
25724/25724 - 0s - loss: 0.1808 - acc: 0.7391
Epoch 29/50
25724/25724 - 0s - loss: 0.1801 - acc: 0.7399
Epoch 30/50
25724/25724 - 1s - loss: 0.1798 - acc: 0.7409
Epoch 31/50
25724/25724 - 1s - loss: 0.1802 - acc: 0.7409
Epoch 32/50
25724/25724 - 0s - loss: 0.1807 - acc: 0.7404
Epoch 33/50
25724/25724 - 1s - loss: 0.1804 - acc: 0.7395
Epoch 34/50
25724/25724 - 1s - loss: 0.1800 - acc: 0.7407
Epoch 35/50
25724/25724 - 1s - loss: 0.1800 - acc: 0.7408
Epoch 36/50
25724/25724 - 0s - loss: 0.1801 - acc: 0.7407
Epoch 37/50
25724/25724 - 0s - loss: 0.1803 - acc: 0.7404
Epoch 38/50
25724/25724 - 1s - loss: 0.1804 - acc: 0.7401
Epoch 39/50
25724/25724 - 1s - loss: 0.1803 - acc: 0.7401
Epoch 40/50
25724/25724 - 1s - loss: 0.1801 - acc: 0.7404
Epoch 41/50
25724/25724 - 1s - loss: 0.1801 - acc: 0.7407
Epoch 42/50
25724/25724 - 0s - loss: 0.1804 - acc: 0.7400
Epoch 43/50
25724/25724 - 0s - loss: 0.1796 - acc: 0.7409
Epoch 44/50
25724/25724 - 1s - loss: 0.1801 - acc: 0.7409
Epoch 45/50
25724/25724 - 1s - loss: 0.1801 - acc: 0.7407
Epoch 46/50
25724/25724 - 0s - loss: 0.1802 - acc: 0.7407
Epoch 47/50
25724/25724 - 0s - loss: 0.1803 - acc: 0.7400
Epoch 48/50
25724/25724 - 1s - loss: 0.1798 - acc: 0.7408
Epoch 49/50
25724/25724 - 0s - loss: 0.1801 - acc: 0.7412
Epoch 50/50
25724/25724 - 0s - loss: 0.1798 - acc: 0.7400

#### Alternative Model 2

In [37]:
# Define the the number of inputs (features) to the model
number_input_features = len(X_train.iloc[0])

# Review the number of features
number_input_features

116

In [38]:
# Define the number of neurons in the output layer
number_output_neurons_A2 = 40
# YOUR CODE HERE

In [39]:
# Define the number of hidden nodes for the first hidden layer
hidden_nodes_layer1_A2 = 35 
# YOUR CODE HERE

In [40]:
# Review the number of hidden nodes in the first layer
hidden_nodes_layer1_A2

35

In [41]:
# Create the Sequential model instance
nn_A2 = Sequential()
# YOUR CODE HERE

In [42]:
# First hidden layer
# YOUR CODE HERE
nn_A2.add
Dense(input_dim=number_input_features, units=hidden_nodes_layer1_A2, activation="relu")

# Output layer
# YOUR CODE HERE
nn_A2.add(Dense(units=number_output_neurons_A2, activation="linear"))
# Check the structure of the model
# YOUR CODE HERE

In [55]:
# Compile the model
# YOUR CODE HERE
nn_A2.compile(loss="mean_squared_error", optimizer="adam", metrics=["binary_accuracy"])

In [56]:
#fit_model_A1 = nn_A1.fit(X_train_scaled, y_train, epochs=50, verbose=2)

In [57]:
# Fit the model
# YOUR CODE HERE
model_2 = nn_A2.fit(X_train_scaled, y_train, epochs=50, verbose=2)

Epoch 1/50
25724/25724 - 0s - loss: 0.2039 - binary_accuracy: 0.7188
Epoch 2/50
25724/25724 - 0s - loss: 0.2011 - binary_accuracy: 0.7203
Epoch 3/50
25724/25724 - 0s - loss: 0.2006 - binary_accuracy: 0.7190
Epoch 4/50
25724/25724 - 0s - loss: 0.2014 - binary_accuracy: 0.7187
Epoch 5/50
25724/25724 - 0s - loss: 0.2036 - binary_accuracy: 0.7185
Epoch 6/50
25724/25724 - 0s - loss: 0.2026 - binary_accuracy: 0.7183
Epoch 7/50
25724/25724 - 0s - loss: 0.2017 - binary_accuracy: 0.7197
Epoch 8/50
25724/25724 - 0s - loss: 0.2020 - binary_accuracy: 0.7194
Epoch 9/50
25724/25724 - 0s - loss: 0.2017 - binary_accuracy: 0.7209
Epoch 10/50
25724/25724 - 0s - loss: 0.2028 - binary_accuracy: 0.7209
Epoch 11/50
25724/25724 - 0s - loss: 0.2024 - binary_accuracy: 0.7190
Epoch 12/50
25724/25724 - 0s - loss: 0.2020 - binary_accuracy: 0.7201
Epoch 13/50
25724/25724 - 0s - loss: 0.2014 - binary_accuracy: 0.7193
Epoch 14/50
25724/25724 - 0s - loss: 0.2027 - binary_accuracy: 0.7194
Epoch 15/50
25724/25724 - 0s - loss: 0.2022 - binary_accuracy: 0.7194
Epoch 16/50
25724/25724 - 0s - loss: 0.2022 - binary_accuracy: 0.7200
Epoch 17/50
25724/25724 - 0s - loss: 0.2019 - binary_accuracy: 0.7204
Epoch 18/50
25724/25724 - 0s - loss: 0.2022 - binary_accuracy: 0.7200
Epoch 19/50
25724/25724 - 0s - loss: 0.2022 - binary_accuracy: 0.7175
Epoch 20/50
25724/25724 - 0s - loss: 0.2021 - binary_accuracy: 0.7200
Epoch 21/50
25724/25724 - 0s - loss: 0.2027 - binary_accuracy: 0.7204
Epoch 22/50
25724/25724 - 0s - loss: 0.2022 - binary_accuracy: 0.7200
Epoch 23/50
25724/25724 - 0s - loss: 0.2020 - binary_accuracy: 0.7198
Epoch 24/50
25724/25724 - 0s - loss: 0.2024 - binary_accuracy: 0.7205
Epoch 25/50
25724/25724 - 0s - loss: 0.2023 - binary_accuracy: 0.7197
Epoch 26/50
25724/25724 - 0s - loss: 0.2022 - binary_accuracy: 0.7198
Epoch 27/50
25724/25724 - 0s - loss: 0.2020 - binary_accuracy: 0.7197
Epoch 28/50
25724/25724 - 0s - loss: 0.2021 - binary_accuracy: 0.7200
Epoch 29/50
25724/25724 - 0s - loss: 0.2021 - binary_accuracy: 0.7200
Epoch 30/50
25724/25724 - 0s - loss: 0.2025 - binary_accuracy: 0.7184
Epoch 31/50
25724/25724 - 0s - loss: 0.2021 - binary_accuracy: 0.7189
Epoch 32/50
25724/25724 - 0s - loss: 0.2029 - binary_accuracy: 0.7194
Epoch 33/50
25724/25724 - 0s - loss: 0.2025 - binary_accuracy: 0.7192
Epoch 34/50
25724/25724 - 0s - loss: 0.2021 - binary_accuracy: 0.7201
Epoch 35/50
25724/25724 - 0s - loss: 0.2025 - binary_accuracy: 0.7194
Epoch 36/50
25724/25724 - 0s - loss: 0.2030 - binary_accuracy: 0.7197
Epoch 37/50
25724/25724 - 0s - loss: 0.2020 - binary_accuracy: 0.7192
Epoch 38/50
25724/25724 - 0s - loss: 0.2018 - binary_accuracy: 0.7195
Epoch 39/50
25724/25724 - 0s - loss: 0.2020 - binary_accuracy: 0.7191
Epoch 40/50
25724/25724 - 0s - loss: 0.2025 - binary_accuracy: 0.7188
Epoch 41/50
25724/25724 - 0s - loss: 0.2025 - binary_accuracy: 0.7195
Epoch 42/50
25724/25724 - 0s - loss: 0.2018 - binary_accuracy: 0.7202
Epoch 43/50
25724/25724 - 0s - loss: 0.2024 - binary_accuracy: 0.7199
Epoch 44/50
25724/25724 - 0s - loss: 0.2029 - binary_accuracy: 0.7187
Epoch 45/50
25724/25724 - 1s - loss: 0.2021 - binary_accuracy: 0.7192
Epoch 46/50
25724/25724 - 1s - loss: 0.2017 - binary_accuracy: 0.7190
Epoch 47/50
25724/25724 - 1s - loss: 0.2021 - binary_accuracy: 0.7194
Epoch 48/50
25724/25724 - 1s - loss: 0.2021 - binary_accuracy: 0.7194
Epoch 49/50
25724/25724 - 0s - loss: 0.2032 - binary_accuracy: 0.7195
Epoch 50/50
25724/25724 - 0s - loss: 0.2019 - binary_accuracy: 0.7217

### Step 2: After finishing your models, display the accuracy scores achieved by each model, and compare the results.

# Evaluate the model using the test data
model_loss, model_accuracy = nn_imported.evaluate(X_test_scaled, y_test, verbose=2)

# Display evaluation results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

In [79]:
print("Original Model Results")

# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled, y_test, verbose=2)
# YOUR CODE HERE

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Original Model Results
8575/8575 - 0s - loss: 0.5576 - acc: 0.7279
Loss: 0.5576005564973237, Accuracy: 0.7279300093650818

In [80]:
print("Alternative Model 1 Results")

# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn_A1.evaluate(X_test_scaled, y_test, verbose=2)
# YOUR CODE HERE

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Alternative Model 1 Results
8575/8575 - 0s - loss: 0.1867 - acc: 0.7329
Loss: 0.18667079858286387, Accuracy: 0.7329446077346802

In [81]:
print("Alternative Model 2 Results")

# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn_A2.evaluate(X_test_scaled, y_test, verbose=2)
# YOUR CODE HERE

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Alternative Model 2 Results
8575/8575 - 0s - loss: 0.2120 - binary_accuracy: 0.7204
Loss: 0.21203978427645068, Accuracy: 0.7203702330589294

### Step 3: Save each of your alternative models as an HDF5 file.

In [ ]:
# Set the file path for the first alternative model
file_path = # YOUR CODE HERE

# Export your model to a HDF5 file
# YOUR CODE HERE

In [ ]:
# Set the file path for the second alternative model
file_path = # YOUR CODE HERE

# Export your model to a HDF5 file
# YOUR CODE HERE